version: 2.1

description: Delta Reek reports

orbs:
  dscar: naokikimura/dscar@0.7.1

executors:
  default:
    description: Default Reek execution environment
    parameters:
      docker-image:
        description: Specify the image used to execute Reek
        type: string
        default: circleci/ruby:latest-node
      resource_class:
        description: Amount of CPU and RAM allocated to each container in a job.
        type: string
        default: small
    docker:
      - image: << parameters.docker-image >>
    resource_class: << parameters.resource_class >>

commands:
  analyze:
    description: Analyze code statically using Reek
    parameters:
      starting-points:
        description: Specify the path of starting to search for files to analyze (Multiple paths can be specified by separating them with line feed)
        type: string
        default: "."
      no-analysis-output-timeout:
        description: Elapsed time the command can run without output. The string is a decimal with unit suffix, such as “20m”, “1.25h”, “5s”
        type: string
        default: 10m
      prepare:
        description: Specify the required steps before analysis if necessary
        type: steps
        default:
          - run: sudo gem install reek
      redirecting-output:
        description: Specify "/dev/null" if you do not want to display the analysis results on the standard output
        type: enum
        enum: ["/dev/stdout", "/dev/stderr", "/dev/null"]
        default: "/dev/null"
    steps:
      - dscar/analyze:
          step-name: Analyze code statically using Reek
          prepare: << parameters.prepare >>
          analysis-command: reek
          analysis-arguments: -f xml
          starting-points: << parameters.starting-points >>
          no-output-timeout: << parameters.no-analysis-output-timeout >>
          redirecting-output: << parameters.redirecting-output >>

jobs:
  analyze:
    description: Analyze code statically using Reek and then evaluate the result
    parameters:
      executor:
        description: Specify the image used to execute analysis
        type: executor
        default: default
      is-target-branch-base:
        description: Check-out the BASE branch if true is specified
        type: boolean
        default: false
      has-reconstructed:
        description: Specify true if `compare-url/reconstruct` has not been executed yet
        type: boolean
        default: false
      attach-compare-url-workspace:
        description: "Attach a workspace for this command to use? Useful when `compare-url` orb's `reconstruct` job is called upstream in a given workflow"
        type: boolean
        default: false
      analyze:
        description: Specify analysis steps
        type: steps
        default:
          - analyze
      analysis-results-path:
        description: Specify the path to save the analysis results if you need to change it
        type: string
        default: "/tmp/analysis-results"
      test-results-path:
        description: Specify the value of the path parameter in the store_test_results step if you need to change it
        type: string
        default: "/tmp/test-results"
      vcs-api-token:
        description: Specify the environment variable name where the VCS (Version Control System) API token is set.
        type: env_var_name
        default: GITHUB_TOKEN
    executor: << parameters.executor >>
    steps:
      - dscar/analyze-and-evaluate:
          is-target-branch-base: << parameters.is-target-branch-base >>
          has-reconstructed: << parameters.has-reconstructed >>
          attach-compare-url-workspace: << parameters.attach-compare-url-workspace >>
          analysis-name: Reek
          analyze: << parameters.analyze >>
          analysis-results-path: << parameters.analysis-results-path >>
          test-results-path: << parameters.test-results-path >>
          vcs-api-token: << parameters.vcs-api-token >>
  calculate:
    description: |
      Calculate the difference between the analysis results and then evaluate the result

      Use the [checkstyle-reports-combiner][1] command to calculate the difference

      [1]: https://www.npmjs.com/package/junit-reports-combiner
    parameters:
      executor:
        description: Specify the image used to execute analysis
        type: executor
        default: default
      calculate:
        description: Specify the steps for calculating the difference
        type: steps
        default:
          - dscar/calculate
      analysis-results-path:
        description: Specify the path to save the analysis results if you need to change it
        type: string
        default: "/tmp/analysis-results"
      test-results-path:
        description: Specify the value of the path parameter in the store_test_results step if you need to change it
        type: string
        default: "/tmp/test-results"
      vcs-api-token:
        description: Specify the environment variable name where the VCS (Version Control System) API token is set.
        type: env_var_name
        default: GITHUB_TOKEN
    executor: << parameters.executor >>
    steps:
      - dscar/calculate-and-evaluate:
          analysis-name: Reek
          calculate: << parameters.calculate >>
          analysis-results-path: << parameters.analysis-results-path >>
          test-results-path: << parameters.test-results-path >>
          vcs-api-token: << parameters.vcs-api-token >>
  execute:
    description: Calculate the difference of Reek results between HEAD branch and BASE branch and then evaluate the result
    parameters:
      executor:
        description: Specify the image used to execute analysis
        type: executor
        default: default
      has-reconstructed:
        description: Specify true if `compare-url/reconstruct` has not been executed yet
        type: boolean
        default: false
      attach-compare-url-workspace:
        description: "Attach a workspace for this command to use? Useful when `compare-url` orb's `reconstruct` job is called upstream in a given workflow"
        type: boolean
        default: false
      analyze:
        description: Specify analysis steps
        type: steps
        default:
          - analyze:
              prepare: []
      analysis-results-path:
        description: Specify the path to save the analysis results if you need to change it
        type: string
        default: "/tmp/analysis-results"
      calculate:
        description: Specify the steps for calculating the difference
        type: steps
        default:
          - dscar/calculate
      test-results-path:
        description: Specify the value of the path parameter in the store_test_results step if you need to change it
        type: string
        default: "/tmp/test-results"
      vcs-api-token:
        description: Specify the environment variable name where the VCS (Version Control System) API token is set.
        type: env_var_name
        default: GITHUB_TOKEN
    executor: << parameters.executor >>
    steps:
      - run: sudo gem install reek
      - dscar/execute-and-evaluate:
          has-reconstructed: << parameters.has-reconstructed >>
          attach-compare-url-workspace: << parameters.attach-compare-url-workspace >>
          analysis-name: Reek
          analyze: << parameters.analyze >>
          analysis-results-path: << parameters.analysis-results-path >>
          calculate: << parameters.calculate >>
          test-results-path: << parameters.test-results-path >>
          vcs-api-token: << parameters.vcs-api-token >>
